#def func(x):
 # res = 0
#  for i in range(x):
  #   res += i
 # return res
#print(func(4))
#print(1)
#raise ValueError
#print(2)
#try:
#  print(1 / 0)
#except ZeroDivisionError:
#  raise ValueError
try:
    num= 5/0
except:
    print("an error occured!!")
    raise